//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OptiScaler.rc
//
#include "resource_build_date.h"

#define VS_VERSION_INFO                 1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

#define STRINGIZE_(s) #s
#define STRINGIZE(s) STRINGIZE_(s)

#define VER_MAJOR_VERSION   0
#define VER_MINOR_VERSION   7
#define VER_HOTFIX_VERSION  7
#define VER_BUILD_NUMBER    6

#define VER_PRE_RELEASE     

#define VER_FILE_VERSION    VER_MAJOR_VERSION, VER_MINOR_VERSION, VER_HOTFIX_VERSION, VER_BUILD_NUMBER
#define VER_FILE_VERSION_STR    STRINGIZE(VER_MAJOR_VERSION) "." STRINGIZE(VER_MINOR_VERSION) "." STRINGIZE(VER_HOTFIX_VERSION) "." STRINGIZE(VER_BUILD_NUMBER) 

#define VER_PRODUCT_VERSION         VER_FILE_VERSION

#ifdef VER_PRE_RELEASE
#define VER_PRODUCT_VERSION_STR     STRINGIZE(VER_MAJOR_VERSION) "." STRINGIZE(VER_MINOR_VERSION) "." STRINGIZE(VER_HOTFIX_VERSION) "-pre" STRINGIZE(VER_BUILD_NUMBER)  " (" VER_BUILD_DATE ")"
#else
#define VER_PRODUCT_VERSION_STR     STRINGIZE(VER_MAJOR_VERSION) "." STRINGIZE(VER_MINOR_VERSION) "." STRINGIZE(VER_HOTFIX_VERSION) "-final"
#endif // VER_PRE_RELEASE

#define VER_PRODUCT_NAME		"OptiScaler v" VER_PRODUCT_VERSION_STR 

